config/routes.rb
Rails.application.routes.draw do
  
  resources :newsletter_subscribers
  resources :blogs
  resources :makers
  resources :subscribers
  resources :staffs
  resources :ticks do
  	collection do 
  		match 'completed', :via => [:get]
  	end	
  end
  devise_for :users, controllers: { registrations: "registrations"}
  resources :tasks

  # match 'ticks/completed' => 'ticks#completed', :via => [:get],:as => 'completed_ticks'

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", :to => 'pages#home'
  get "/pricing", :to => 'pages#pricing'
  get "/about", :to => 'pages#about'
  get "/enterprise", :to => 'pages#enterprise'
  get "/privacy", :to => 'pages#privacy'
  get "/team", :to => 'pages#team'
  get "/support", :to => 'pages#support'
  get "/features", :to => 'pages#features'
  get "/chef", :to => 'pages#home'
  get "/time", :to => 'pages#time'

  get "/blog", :to => 'blogs#index'
  get "/tour", :to => 'subscribers#tour'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tasks
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/maker.rb
class Maker < ApplicationRecord
	validates_presence_of :first_name, message: "Please enter your first name."
    validates_presence_of :last_name, message: "Please enter your surname."
    validates_presence_of :email, message: "Please enter an email address"

    validates_format_of :email, :with => Devise::email_regexp, message: '...this doesn\'t look like an email address'

end

app/models/regularity.rb
class Regularity < ApplicationRecord
	has_many :tasks
	has_many :ticks
end

app/models/staff.rb
class Staff < ApplicationRecord
	has_many :ticks
	belongs_to :user

	validates_presence_of :first_name, message: 'Please enter a first name'
	validates_presence_of :surname, message: 'Please enter a surname'
	validates_presence_of :email, message: 'Please enter a email address'
	validates_presence_of :job_title, message: 'Please enter a job title'

	validates_format_of :email,:with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :ticks
	belongs_to :regularity

	validates :name, presence: true
	validates :regularity_id, presence: true
	validates :category_id, presence: true

	validate :has_content

  	def has_content
  		if starting == false && midday == false && ending == false
    		errors[:base] = "You must select one"
  		end
	end
end

app/models/tick.rb
class Tick < ApplicationRecord
	belongs_to :task
	belongs_to :user
	belongs_to :regularity

	belongs_to :staff

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |tick|
				csv << tick.attributes.values_at(*column_names)
			end
		end
	end

end

app/models/tick_search.rb
class TickSearch
	attr_reader :date_from, :date_to

	def initialize(params)
		params ||= {}
		# @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
		@date_to = parsed_date(params[:date_to], Date.today.to_s)
	end

	def scope 
		Tick.where(date: @date_to)
	end

	private

	def parsed_date(date_string, default)
		# Date.parse(date_string)
		Date.strptime("%m/%d/%Y")
	rescue ArgumentError, TypeError
		default
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasks
	has_many :ticks
	has_many :staff
  	
 #  	after_create :send_welcome_mail

 #  	def send_welcome_mail
 #  		UserMailer.signup_confirmation(@user).deliver
	# end
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable

    validates_presence_of :first_name, message: "Please enter your first name."
    validates_presence_of :last_name, message: "Please enter your surname."
    validates_presence_of :email, message: "Please enter an email address"
    # validates_presence_of :organisation, message: "What's your place called?"
    

    validates_format_of :email, :with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
    @title = "Staff"
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = current_user.staff.build
    @title = "Create New Staff"
  end

  # GET /staffs/1/edit
  def edit
    @title = "Update Staff"
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = current_user.staff.build(staff_params)

    respond_to do |format|
      if @staff.valid?
        @staff.save!
        format.html { redirect_to staffs_path, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to staffs_path, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:first_name, :surname, :email, :job_title, :manager, :pin, :user_id, :former, :former_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/form_helper.rb
module FormHelper
	def errors_for(form, field)
		content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
	end

	# def form_group_for(form, field)
	# 	has_errors = form.object.errors[field].present?
		
	# 	content_tag :div, class: "form-group #{'has-error' if has_errors}" do
	# 		concat form.label(field, class: 'control-label')
	# 		concat capture(&block)
	# 		concat errors_for(form, field)
	# 	end
	# end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/ticks_helper.rb
module TicksHelper
end

app/views/staffs/_form.html.erb
<%= simple_form_for @staff, validate: true do |f| %>
  <%= f.error_notification %>
    
      <br>
      <div class="first-name">
         <%= f.input :first_name, required: true, autofocus: true, label: false , placeholder: true %>
      </div>
      <div class="last-name">
         <%= f.input :surname, required: true, label: false, placeholder: true %>
      </div>
      <%= f.input :email, label: false, placeholder: true %>
      <%= f.input :job_title, label: false, placeholder: true %>
      <%= f.input :manager %>

    <div class="new-btn">
      <%= f.button :submit, :class => 'btn-primary btn-block btn-lg' %>
    </div>

<% end %>

app/views/staffs/edit.html.erb
<div class="form-container">
	<div class="col-md-6 col-md-offset-3 well signin">
		<div class="back-btn">
			<%= link_to staffs_path do %>
				<span class="glyphicon glyphicon-chevron-left"></span> <p><%= t 'staffs.edit.back' %></p>
			<% end %>
		</div>
		
			<br>
			<h4><i class="fa fa-users"></i> <%= t 'staffs.edit.title' %></h4>

			<%= simple_form_for @staff, validate: true do |f| %>
			  <%= f.error_notification %>
			  <% if @staff.former? %>
			    	<p><%= @staff.first_name %> <%= @staff.surname%> 
			    		<% if @staff.manager? %>
			    			(Manager)
			    		<% end %>
		    			left on <%= @staff.former_date %>.
		    		</p>

			    	<p>Job Title: <%= @staff.job_title %></p>
			    	<p>To reactivate this staff member, leave this box unchecked:</p>
			    	<%= f.input :former %>
			    <% else %>

			  
			    <br>
			    <div class="first-name">
			       <%= f.input :first_name, required: true, autofocus: true, label: false , placeholder: "First name (required)" %>
			    </div>
			    <div class="last-name">
			       <%= f.input :surname, required: true, label: false, placeholder: "Last name (required)" %>
			  </div>
			    <%= f.input :email, label: false, placeholder: "Email" %>
			    <%= f.input :job_title, label: false, placeholder: "Job Title" %>
			    <%= f.input :manager %>
			    <div id="showmenu" class="change-password-wrap"><p>Click here if <%= @staff.first_name %> has left.</p></div>
                  <div class="menu" style="display: none;">
                    <div class="change-password former-staff">
                      <h4>Former staff member:</h4>

                      	<p>(Check the box if this <%= @staff.first_name %> has left)</p>
                    	<%= f.input :former %>
			    		<%= f.input :former_date, label: "#{@staff.first_name} left on:" %>
                    </div>
                  </div>
			    <% end %>

			  <div class="new-btn">
			    <%= f.button :submit, :class => 'btn-primary btn-block btn-lg' %>
			  </div>
			<% end %>
	</div>
</div>
<script type="text/javascript">

    $(document).ready(function() {
        $('#showmenu').click(function() {
                $('.menu').slideToggle("fast");
        });
    });

</script>

app/views/staffs/index.html.erb
<% if user_signed_in? %>
<div class="page-content" id="main-container">
  <div class="row">
    <div class="col-sm-6">
      <div class="container">
        <h1 data-step="1" data-intro="This is your staff page."><%= t "staffs.index.title" %></h1>
      </div>  
    </div>
    <div class="col-sm-6">
      <div class="create-btn-container">
        <div class="new-btn">
          <%= link_to new_staff_path, :class => 'waves-effect btn-large' do %>
          + <%= t "staffs.index.btn" %>
          <% end %>
        </div>
      </div>  
    </div>
  </div>  
  <hr>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well signin">
        <h4><%= t "staffs.index.table.table_title" %></h4>
       <div class="table-responsive"> 
        <table class="table table-hover">
          <thead>
            <th><%= t "staffs.index.table.name" %></th>
            <th><%= t "staffs.index.table.manager" %></th>
            <th><%= t "staffs.index.table.job_title" %></th>
            <th><%= t "staffs.index.table.edit" %></th>
          </thead>
          <tbody>
            <% @staffs.each do |staff| %>
              <% if staff.user_id == current_user.id && !staff.former %>
                <tr>
                  <td><%= staff.first_name%> <%= staff.surname %></td>
                  <td>
                    <% if staff.manager? %>
                      <i class="fa fa-key manager"></i>
                    <% else %>
                      <p>-</p>
                    <% end %>
                  </td>
                  <td>
                    <% if staff.job_title? %>
                      <%= staff.job_title %>
                    <% else %>
                      <p>-</p>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_staff_path(staff) do %>
                      <p class="task-edit"><span class="glyphicon glyphicon-pencil"></span></p>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <hr>
      <div id="showmenu" class="change-password-wrap"><p><%= t "staffs.index.table.former.former_staff_link" %></p></div>
        <div class="menu" style="display: none;">
          <h4><%= t "staffs.index.table.former.former_staff_title" %></h4>
          <div class="table-responsive change-password"> 
            <table class="table table-hover">
              <thead>
                <th><%= t "staffs.index.table.name" %></th>
                <th><%= t "staffs.index.table.manager" %></th>
                <th><%= t "staffs.index.table.leaving_date" %></th>
                <th><%= t "staffs.index.table.job_title" %></th>
                <th><%= t "staffs.index.table.edit" %></th>
              </thead>
              <tbody>
                <% @staffs.each do |staff| %>
                  <% if staff.user_id == current_user.id && staff.former? %>
                    <tr> 
                      <td>
                        <%= staff.first_name%> <%= staff.surname %>
                      </td>
                      <td>
                        <% if staff.manager? %>
                          <i class="fa fa-key manager"></i>
                        <% else %>
                          <p>-</p>
                        <% end %>
                      </td>
                      <td>
                        <%= staff.former_date %>
                      </td>
                      <td>
                        <% if staff.job_title? %>
                          <%= staff.job_title %>
                        <% else %>
                          <p>-</p>
                        <% end %>
                      </td>
                      <td>
                        <%= link_to edit_staff_path(staff) do %>
                          <p class="task-edit"><span class="glyphicon glyphicon-pencil"></span></p>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">

    $(document).ready(function() {
        $('#showmenu').click(function() {
                $('.menu').slideToggle("fast");
        });
    });

</script>
<% end %>

    <script type="text/javascript" src="../../intro.js"></script>
    <script type="text/javascript">
      if (RegExp('multipage', 'gi').test(window.location.search)) {
        introJs().start();
      }
    </script>

app/views/staffs/new.html.erb
<div class="page-content" id="main-container">
	<div class="form-container">
		<div class="col-md-6 col-md-offset-3 well signin">
			<div class="back-btn">
				<%= link_to staffs_path do %>
					<span class="glyphicon glyphicon-chevron-left"></span> <p> <%= t "staffs.new.back" %></p>
				<% end %>
			</div>		
				<br>
				<h4><i class="fa fa-users"></i><%= t 'staffs.new.title' %></h4>
	
				<%= render 'form', staff: @staff %>
				<br>
		</div>
	</div>
</div>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @staff.first_name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @staff.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staff.email %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @staff.job_title %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @staff.manager %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @staff.pin %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>