config/routes.rb
Rails.application.routes.draw do
  
  resources :newsletter_subscribers
  resources :blogs
  resources :makers
  resources :subscribers
  resources :staffs
  resources :ticks do
  	collection do 
  		match 'completed', :via => [:get]
  	end	
  end
  devise_for :users, controllers: { registrations: "registrations"}
  resources :tasks

  # match 'ticks/completed' => 'ticks#completed', :via => [:get],:as => 'completed_ticks'

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", :to => 'pages#home'
  get "/pricing", :to => 'pages#pricing'
  get "/about", :to => 'pages#about'
  get "/enterprise", :to => 'pages#enterprise'
  get "/privacy", :to => 'pages#privacy'
  get "/team", :to => 'pages#team'
  get "/support", :to => 'pages#support'
  get "/features", :to => 'pages#features'
  get "/chef", :to => 'pages#home'
  get "/time", :to => 'pages#time'

  get "/blog", :to => 'blogs#index'
  get "/tour", :to => 'subscribers#tour'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tasks
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/maker.rb
class Maker < ApplicationRecord
	validates_presence_of :first_name, message: "Please enter your first name."
    validates_presence_of :last_name, message: "Please enter your surname."
    validates_presence_of :email, message: "Please enter an email address"

    validates_format_of :email, :with => Devise::email_regexp, message: '...this doesn\'t look like an email address'

end

app/models/newsletter_subscriber.rb
class NewsletterSubscriber < ApplicationRecord

	validates_presence_of :first_name, message: 'Please enter a first name'
	validates_presence_of :email, message: 'Please enter a email address'


	validates_format_of :email,:with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/models/regularity.rb
class Regularity < ApplicationRecord
	has_many :tasks
	has_many :ticks
end

app/models/staff.rb
class Staff < ApplicationRecord
	has_many :ticks
	belongs_to :user

	validates_presence_of :first_name, message: 'Please enter a first name'
	validates_presence_of :surname, message: 'Please enter a surname'
	validates_presence_of :email, message: 'Please enter a email address'
	validates_presence_of :job_title, message: 'Please enter a job title'

	validates_format_of :email,:with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :ticks
	belongs_to :regularity

	validates :name, presence: true
	validates :regularity_id, presence: true
	validates :category_id, presence: true

	validate :has_content

  	def has_content
  		if starting == false && midday == false && ending == false
    		errors[:base] = "You must select one"
  		end
	end
end

app/models/tick.rb
class Tick < ApplicationRecord
	belongs_to :task
	belongs_to :user
	belongs_to :regularity

	belongs_to :staff

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |tick|
				csv << tick.attributes.values_at(*column_names)
			end
		end
	end

end

app/models/tick_search.rb
class TickSearch
	attr_reader :date_from, :date_to

	def initialize(params)
		params ||= {}
		# @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
		@date_to = parsed_date(params[:date_to], Date.today.to_s)
	end

	def scope 
		Tick.where(date: @date_to)
	end

	private

	def parsed_date(date_string, default)
		# Date.parse(date_string)
		Date.strptime("%m/%d/%Y")
	rescue ArgumentError, TypeError
		default
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasks
	has_many :ticks
	has_many :staff
  	
 #  	after_create :send_welcome_mail

 #  	def send_welcome_mail
 #  		UserMailer.signup_confirmation(@user).deliver
	# end
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable

    validates_presence_of :first_name, message: "Please enter your first name."
    validates_presence_of :last_name, message: "Please enter your surname."
    validates_presence_of :email, message: "Please enter an email address"
    # validates_presence_of :organisation, message: "What's your place called?"
    

    validates_format_of :email, :with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/controllers/newsletter_subscribers_controller.rb
class NewsletterSubscribersController < ApplicationController
  before_action :set_newsletter_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /newsletter_subscribers
  # GET /newsletter_subscribers.json
  def index
    @newsletter_subscribers = NewsletterSubscriber.all
  end

  # GET /newsletter_subscribers/1
  # GET /newsletter_subscribers/1.json
  def show
  end

  # GET /newsletter_subscribers/new
  def new
    @newsletter_subscriber = NewsletterSubscriber.new
  end

  # GET /newsletter_subscribers/1/edit
  def edit
  end

  # POST /newsletter_subscribers
  # POST /newsletter_subscribers.json
  def create
    @newsletter_subscriber = NewsletterSubscriber.new(newsletter_subscriber_params)

    respond_to do |format|
      if @newsletter_subscriber.save
        BlogSubscribersMailer.email_confirmation(@newsletter_subscriber).deliver!
        format.html { redirect_to blogs_path, notice: 'Newsletter subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @newsletter_subscriber }
      else
        format.html { render :new }
        format.json { render json: @newsletter_subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletter_subscribers/1
  # PATCH/PUT /newsletter_subscribers/1.json
  def update
    respond_to do |format|
      if @newsletter_subscriber.update(newsletter_subscriber_params)
        format.html { redirect_to @newsletter_subscriber, notice: 'Newsletter subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter_subscriber }
      else
        format.html { render :edit }
        format.json { render json: @newsletter_subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletter_subscribers/1
  # DELETE /newsletter_subscribers/1.json
  def destroy
    @newsletter_subscriber.destroy
    respond_to do |format|
      format.html { redirect_to newsletter_subscribers_url, notice: 'Newsletter subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter_subscriber
      @newsletter_subscriber = NewsletterSubscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_subscriber_params
      params.require(:newsletter_subscriber).permit(:email, :first_name)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/form_helper.rb
module FormHelper
	def errors_for(form, field)
		content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
	end

	# def form_group_for(form, field)
	# 	has_errors = form.object.errors[field].present?
		
	# 	content_tag :div, class: "form-group #{'has-error' if has_errors}" do
	# 		concat form.label(field, class: 'control-label')
	# 		concat capture(&block)
	# 		concat errors_for(form, field)
	# 	end
	# end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/newsletter_subscribers_helper.rb
module NewsletterSubscribersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/ticks_helper.rb
module TicksHelper
end

app/views/newsletter_subscribers/_form.html.erb
<div class="container">
	<div class="col-sm-6 col-sm-offset-3 well signin">
		<h4 class="email-note">Get Fresh Restaurant Marketing Guides, Management Tips, and More from the Minibarra Chef Blog.</h4>
		<br>

		<%= simple_form_for @newsletter_subscriber, validate: true do |f| %>

			<%= f.input :first_name, required: true, autofocus: true, label: false , :class => "input-lg", placeholder: "First name" %>
			<%= f.input :email, required: true, label: false, placeholder: "Email (required)" %>
			<p class="email-note"><span class="glyphicon glyphicon-lock"></span> We hate spam and promise to keep your email address safe.</p> 
			<%= f.button :submit, "Subscribe", class: 'btn-primary btn-block btn-lg' %>


		<% end %>

<br>
<%= flash_messages layout_flash: false %>

</div>
</div>

app/views/newsletter_subscribers/edit.html.erb
<h1>Editing Newsletter Subscriber</h1>

<%= render 'form', newsletter_subscriber: @newsletter_subscriber %>

<%= link_to 'Show', @newsletter_subscriber %> |
<%= link_to 'Back', newsletter_subscribers_path %>

app/views/newsletter_subscribers/index.html.erb
<% if user_signed_in? && current_user.admin == true %>
  <p id="notice"><%= notice %></p>

  <h1>Newsletter Subscribers</h1>

  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>First name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @newsletter_subscribers.each do |newsletter_subscriber| %>
        <tr>
          <td><%= newsletter_subscriber.email %></td>
          <td><%= newsletter_subscriber.first_name %></td>
          <td><%= link_to 'Show', newsletter_subscriber %></td>
          <td><%= link_to 'Edit', edit_newsletter_subscriber_path(newsletter_subscriber) %></td>
          <td><%= link_to 'Destroy', newsletter_subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Newsletter Subscriber', new_newsletter_subscriber_path %>
<% end %>

app/views/newsletter_subscribers/new.html.erb
<div class="dark-background">

	<%= render 'form', newsletter_subscriber: @newsletter_subscriber %>

</div>

app/views/newsletter_subscribers/show.html.erb
<% if user_signed_in? && current_user.admin == true %>	
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Email:</strong>
	  <%= @newsletter_subscriber.email %>
	</p>

	<p>
	  <strong>First name:</strong>
	  <%= @newsletter_subscriber.first_name %>
	</p>

	<%= link_to 'Edit', edit_newsletter_subscriber_path(@newsletter_subscriber) %> |
	<%= link_to 'Back', newsletter_subscribers_path %>
<% end %>