config/routes.rb
Rails.application.routes.draw do
  
  resources :newsletter_subscribers
  resources :blogs
  resources :makers
  resources :subscribers
  resources :staffs
  resources :ticks do
  	collection do 
  		match 'completed', :via => [:get]
  	end	
  end
  devise_for :users, controllers: { registrations: "registrations"}
  resources :tasks

  # match 'ticks/completed' => 'ticks#completed', :via => [:get],:as => 'completed_ticks'

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", :to => 'pages#home'
  get "/pricing", :to => 'pages#pricing'
  get "/about", :to => 'pages#about'
  get "/enterprise", :to => 'pages#enterprise'
  get "/privacy", :to => 'pages#privacy'
  get "/team", :to => 'pages#team'
  get "/support", :to => 'pages#support'
  get "/features", :to => 'pages#features'
  get "/chef", :to => 'pages#home'
  get "/time", :to => 'pages#time'

  get "/blog", :to => 'blogs#index'
  get "/tour", :to => 'subscribers#tour'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tasks
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/maker.rb
class Maker < ApplicationRecord
	validates_presence_of :first_name, message: "Please enter your first name."
    validates_presence_of :last_name, message: "Please enter your surname."
    validates_presence_of :email, message: "Please enter an email address"

    validates_format_of :email, :with => Devise::email_regexp, message: '...this doesn\'t look like an email address'

end

app/models/regularity.rb
class Regularity < ApplicationRecord
	has_many :tasks
	has_many :ticks
end

app/models/staff.rb
class Staff < ApplicationRecord
	has_many :ticks
	belongs_to :user

	validates_presence_of :first_name, message: 'Please enter a first name'
	validates_presence_of :surname, message: 'Please enter a surname'
	validates_presence_of :email, message: 'Please enter a email address'
	validates_presence_of :job_title, message: 'Please enter a job title'

	validates_format_of :email,:with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :ticks
	belongs_to :regularity

	validates :name, presence: true
	validates :regularity_id, presence: true
	validates :category_id, presence: true

	validate :has_content

  	def has_content
  		if starting == false && midday == false && ending == false
    		errors[:base] = "You must select one"
  		end
	end
end

app/models/tick.rb
class Tick < ApplicationRecord
	belongs_to :task
	belongs_to :user
	belongs_to :regularity

	belongs_to :staff

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |tick|
				csv << tick.attributes.values_at(*column_names)
			end
		end
	end

end

app/models/tick_search.rb
class TickSearch
	attr_reader :date_from, :date_to

	def initialize(params)
		params ||= {}
		# @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
		@date_to = parsed_date(params[:date_to], Date.today.to_s)
	end

	def scope 
		Tick.where(date: @date_to)
	end

	private

	def parsed_date(date_string, default)
		# Date.parse(date_string)
		Date.strptime("%m/%d/%Y")
	rescue ArgumentError, TypeError
		default
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasks
	has_many :ticks
	has_many :staff
  	
 #  	after_create :send_welcome_mail

 #  	def send_welcome_mail
 #  		UserMailer.signup_confirmation(@user).deliver
	# end
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable

    validates_presence_of :first_name, message: "Please enter your first name."
    validates_presence_of :last_name, message: "Please enter your surname."
    validates_presence_of :email, message: "Please enter an email address"
    # validates_presence_of :organisation, message: "What's your place called?"
    

    validates_format_of :email, :with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.order("created_at DESC")
    @title = "Blog | Minibarra Chef"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blogs = Blog.all
    @title = @blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @blog.author = current_user.first_name + " " + current_user.last_name
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update!(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy!
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :author, :meta_desc, :lead, :image_link, :reading_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/form_helper.rb
module FormHelper
	def errors_for(form, field)
		content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
	end

	# def form_group_for(form, field)
	# 	has_errors = form.object.errors[field].present?
		
	# 	content_tag :div, class: "form-group #{'has-error' if has_errors}" do
	# 		concat form.label(field, class: 'control-label')
	# 		concat capture(&block)
	# 		concat errors_for(form, field)
	# 	end
	# end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/ticks_helper.rb
module TicksHelper
end

app/views/blogs/_form.html.erb
      <%= simple_form_for(@blog) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :title %>
          <%= f.input :image_link %>
          <p><strong>Copy and paste your image with this syntax:</strong> ![](https://www.stickyourlinkhere.com/img.jpeg)</p>
          <%= f.input :lead %>
          <%= f.input :content %>
          <%= f.input :reading_time %>
          <p>This blog uses markdown syntax. <a href="https://help.github.com/articles/basic-writing-and-formatting-syntax/">Click here for a basic guide</a>.</p>
          <%= f.input :author %>
          <%= f.input :meta_desc %>
          <p>Link to <a href="http://www.hemingwayapp.com/">Hemmingway App</a></p>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Post" %>
        </div>
      <% end %>

app/views/blogs/edit.html.erb
<% if user_signed_in? && current_user.admin == true %>
	<div class="row container style-links">
		<div class="well signin">
			<% if user_signed_in? && current_user.admin == true %>
			<h1>Editing Post</h1>

			<%= render 'form', blog: @blog %>

			<%= link_to 'Show', @blog %> |
			<%= link_to 'Back', blogs_path %> | 
			<%= link_to 'Destroy', @blog, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</div>	
	</div>
<% end %>

app/views/blogs/index.html.erb
<div class="row blog">
  <div class="col-lg-12 blog-title ">
    <h1>The Minibarra Chef Blog</h1>
    <div class="col-sm-6 col-sm-offset-3">
      <p>Stay ahead of the curve with our 7-part email course on how to get more customers in your restaurant </p>

    </div>
  </div>
</div>
<div class="container">
  <div class="col-sm-8">
    <!-- Blog Post -->
    <% @blogs.each do |blog| %>
    <!-- Title -->
    <div class="blog-title-link">
      <h2><%= link_to blog.title, blog %></h2>
    </div>
    <!-- Author -->
    <hr>
    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted on <%= blog.created_at.strftime("%e %B %Y") %> by <%= blog.author %> | <%= blog.reading_time %> min read</p>
    <hr>
    <div class="lead-img">
      <p><%= markdown(blog.image_link) %></p>
    </div>
    <!-- Post Content -->
    <div class="content">
      <%= markdown(blog.lead) %>
    </div>
    <div class="read-link">
      <%= link_to "Read now", blog %>
      <% if user_signed_in? && current_user.admin == true %>
       | 
        <%= link_to edit_blog_path(blog) do %> 
          <i class="glyphicon glyphicon-pencil"></i> Edit Post
        <% end %> 

        <%= link_to 'Destroy', blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    <br>
    <hr>
    <% end %>
  </div>
  <!-- Blog Sidebar Widgets Column -->
  <div class="col-sm-4">
    <!-- Blog Categories Well -->
    <div class="well start-here" style="margin-top: 20px;">
      <h4>New? Start here</h4>
      <p>A blog about marketing, managing, and all things food & beverage. Insights, tips, and best practices. </p>

      <div class="blog-side-links">
          <p><a href="#">How To Use A Blog To Generate More Business</a></p>
          <p><a href="#">Don't Make The Same Mistake Harrods Made. Why Your Staff Deserve Their Tips.</a></p>
          <p><a href="#">A Suppliers Guide To Choosing The Right Suppliers</a></p>
      </div>

      <div class="read-link">
        <% if user_signed_in? && current_user.admin == true %>
        <%= link_to new_blog_path do %> 
        <i class="glyphicon glyphicon-pencil"></i> New Post
        <% end %> 
        <% end %>
      </div>
    </div>

    <div class="well email-signup">
        <h2>The Ultimate Guide to Starting a Restaurant</h2>
        <hr>
        <p>A 7-part email course with everything you need to know. Get started with a few of our popular posts:</p>
        <br>
        <div class="new-btn">
            <a class="btn-primary btn-block btn-lg faa-parent animated-hover" href="/newsletter_subscribers/new">
              <i class="glyphicon glyphicon-hand-right faa-shake"></i>  Get Started
            </a>
        </div>
    </div>
    <div class="well recent-blogs" style="margin-top: 20px;">
      <h4>Recent Posts</h4>
      <div class="blog-side-links">
        <% @blogs.each do |blog| %>
          <p>
            <%= link_to blog.title, blog %>, by <%= blog.author %> (<%= blog.created_at.strftime("%B %Y") %> | <%= blog.reading_time %> min read)
          </p>
        <% end %>
      </div>
      <div class="read-link">
        <% if user_signed_in? && current_user.admin == true %>
        <%= link_to new_blog_path do %> 
         <i class="glyphicon glyphicon-pencil"></i> New Post
        <% end %> 
        <% end %>
      </div>
    </div>    
    <!-- /.row -->
  </div>
</div>
<!-- /.container -->
<p id="notice"><%= notice %></p>

app/views/blogs/new.html.erb
<% if user_signed_in? && current_user.admin == true %>
	<div class="row container style-links">
		<div class="well signin">
			<h1>New Blog</h1>
		
			<%= render 'form', blog: @blog %>
			<%= link_to 'Back', blogs_path %>
		</div>
	</div>
<% end %>	

app/views/blogs/show.html.erb
<div class="container">
    <div class="row">
        <!-- Blog Post Content Column -->
        <div class="col-sm-8">
            <!-- Blog Post -->
            <!-- Title -->
            <h1><%= @blog.title %></h1>
            <!-- Author -->
            <p class="lead">
                by <%= @blog.author %>
            </p>
            <hr>
            <!-- Date/Time -->
            <div class="read-link">
                <p><span class="glyphicon glyphicon-time"></span> <%= @blog.created_at.strftime("%e %B %Y") %> | <%= @blog.reading_time %> min read</p>
                <% if user_signed_in? && current_user.admin == true %>
                    <%= link_to edit_blog_path(@blog) do %> 
                        <i class="glyphicon glyphicon-pencil"></i> Edit Post
                     <% end %>    
                       |        
                     <%= link_to @blog, method: :delete, data: { confirm: 'Are you sure?' } do %>         
                        <i class="glyphicon glyphicon-trash"></i> Delete
                     <% end %>
                <% end %>
            </div>    
            <hr>

            <!-- Preview Image -->
            <div class="lead-img">
                <p><%= markdown(@blog.image_link) %></p>
            </div>
            <!-- Post Content -->
            <div class="lead">
                <%= markdown(@blog.lead) %>
            </div>
            
            <div class="content">
                <%= markdown(@blog.content) %>
            </div>
            <hr>


            
            <% if user_signed_in? %>
                <%= current_user.id %>
            <% end %>
        </div>
        <!-- Blog Sidebar Widgets Column -->
        <div class="col-sm-4">
            <!-- Blog Categories Well -->
            <div class="well start-here" style="margin-top: 20px;">
              <h4>New? Start here</h4>
              <p>A blog about marketing, managing, and all things food & beverage. Insights, tips, and best practices. </p>

              <div class="blog-side-links">
                  <p><a href="#">How To Use A Blog To Generate More Business</a></p>
                  <p><a href="#">Don't Make The Same Mistake Harrods Made. Why Your Staff Deserve Their Tips.</a></p>
                  <p><a href="#">A Suppliers Guide To Choosing The Right Suppliers</a></p>
              </div>

              <div class="read-link">
                <% if user_signed_in? && current_user.admin == true %>
                <%= link_to new_blog_path do %> 
                <i class="glyphicon glyphicon-pencil"></i> New Post
                <% end %> 
                <% end %>
              </div>
            </div>            
            <div class="well email-signup">
                <h2>The Ultimate Guide to Starting a Restaurant</h2>
                <hr>
                <p>A 7-part email course with everything you need to know. Get started with a few of our popular posts:</p>
                <br>
                <div class="new-btn">
                    <a class="btn-primary btn-block btn-lg" href="/newsletter_subscribers/new">
                      <i class="glyphicon glyphicon-hand-right"></i>  Get Started
                    </a>
                </div>
            </div>            
            <div class="well recent-blogs" style="margin-top: 25px;">
                <h4>Recent Posts</h4>
                <div class="blog-side-links">
                    <% @blogs.each do |blog| %>
                        <p>
                            <%= link_to blog.title, blog %>, by <%= blog.author %> (<%= @blog.created_at.strftime("%e %B %Y") %> | <%= blog.reading_time %> min read)
                        </p>
                    <% end %>
                </div>
                <div class="read-link">
                    <% if user_signed_in? && current_user.admin == true %>
                        <%= link_to new_blog_path do %> 
                            <i class="glyphicon glyphicon-pencil"></i> New Post
                        <% end %> 
                    <% end %>
                </div>                    
            </div>
        <!-- /.row -->
        </div>


</div>

    </div>

</div>
<!-- /.container -->