config/routes.rb
Rails.application.routes.draw do
  
  resources :newsletter_subscribers
  resources :blogs
  resources :makers
  resources :subscribers
  resources :staffs
  resources :ticks do
  	collection do 
  		match 'completed', :via => [:get]
  	end	
  end
  devise_for :users, controllers: { registrations: "registrations"}
  resources :tasks

  # match 'ticks/completed' => 'ticks#completed', :via => [:get],:as => 'completed_ticks'

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", :to => 'pages#home'
  get "/pricing", :to => 'pages#pricing'
  get "/about", :to => 'pages#about'
  get "/enterprise", :to => 'pages#enterprise'
  get "/privacy", :to => 'pages#privacy'
  get "/team", :to => 'pages#team'
  get "/support", :to => 'pages#support'
  get "/features", :to => 'pages#features'
  get "/chef", :to => 'pages#home'
  get "/time", :to => 'pages#time'

  get "/blog", :to => 'blogs#index'
  get "/tour", :to => 'subscribers#tour'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tasks
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/maker.rb
class Maker < ApplicationRecord
	validates_presence_of :first_name, message: "Please enter your first name."
    validates_presence_of :last_name, message: "Please enter your surname."
    validates_presence_of :email, message: "Please enter an email address"

    validates_format_of :email, :with => Devise::email_regexp, message: '...this doesn\'t look like an email address'

end

app/models/regularity.rb
class Regularity < ApplicationRecord
	has_many :tasks
	has_many :ticks
end

app/models/staff.rb
class Staff < ApplicationRecord
	has_many :ticks
	belongs_to :user

	validates_presence_of :first_name, message: 'Please enter a first name'
	validates_presence_of :surname, message: 'Please enter a surname'
	validates_presence_of :email, message: 'Please enter a email address'
	validates_presence_of :job_title, message: 'Please enter a job title'

	validates_format_of :email,:with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :ticks
	belongs_to :regularity

	validates :name, presence: true
	validates :regularity_id, presence: true
	validates :category_id, presence: true

	validate :has_content

  	def has_content
  		if starting == false && midday == false && ending == false
    		errors[:base] = "You must select one"
  		end
	end
end

app/models/tick.rb
class Tick < ApplicationRecord
	belongs_to :task
	belongs_to :user
	belongs_to :regularity

	belongs_to :staff

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |tick|
				csv << tick.attributes.values_at(*column_names)
			end
		end
	end

end

app/models/tick_search.rb
class TickSearch
	attr_reader :date_from, :date_to

	def initialize(params)
		params ||= {}
		# @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
		@date_to = parsed_date(params[:date_to], Date.today.to_s)
	end

	def scope 
		Tick.where(date: @date_to)
	end

	private

	def parsed_date(date_string, default)
		# Date.parse(date_string)
		Date.strptime("%m/%d/%Y")
	rescue ArgumentError, TypeError
		default
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasks
	has_many :ticks
	has_many :staff
  	
 #  	after_create :send_welcome_mail

 #  	def send_welcome_mail
 #  		UserMailer.signup_confirmation(@user).deliver
	# end
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable

    validates_presence_of :first_name, message: "Please enter your first name."
    validates_presence_of :last_name, message: "Please enter your surname."
    validates_presence_of :email, message: "Please enter an email address"
    # validates_presence_of :organisation, message: "What's your place called?"
    

    validates_format_of :email, :with => Devise::email_regexp, message: '...this doesn\'t look like an email address'
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
  before_action :set_maker, only: [:show, :edit, :update, :destroy]

  # GET /makers
  # GET /makers.json
  def index
    @makers = Maker.all
  end

  # GET /makers/1
  # GET /makers/1.json
  def show
  end

  # GET /makers/new
  def new
    @maker = Maker.new
    @title = "Experience Design Program | Minibarra Chef"
  end

  # GET /makers/1/edit
  def edit
  end

  # POST /makers
  # POST /makers.json
  def create
    @maker = Maker.new(maker_params)

    respond_to do |format|
      if @maker.save
        MakerMailer.maker_signup_confirmation(@maker).deliver!
        format.html { redirect_to root, notice: 'Maker was successfully created.' }
        format.json { render :show, status: :created, location: @maker }
      else
        format.html { render :new }
        format.json { render json: @maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makers/1
  # PATCH/PUT /makers/1.json
  def update
    respond_to do |format|
      if @maker.update(maker_params)
        format.html { redirect_to @maker, notice: 'Maker was successfully updated.' }
        format.json { render :show, status: :ok, location: @maker }
      else
        format.html { render :edit }
        format.json { render json: @maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makers/1
  # DELETE /makers/1.json
  def destroy
    @maker.destroy
    respond_to do |format|
      format.html { redirect_to makers_url, notice: 'Maker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maker
      @maker = Maker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maker_params
      params.require(:maker).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/form_helper.rb
module FormHelper
	def errors_for(form, field)
		content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
	end

	# def form_group_for(form, field)
	# 	has_errors = form.object.errors[field].present?
		
	# 	content_tag :div, class: "form-group #{'has-error' if has_errors}" do
	# 		concat form.label(field, class: 'control-label')
	# 		concat capture(&block)
	# 		concat errors_for(form, field)
	# 	end
	# end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/ticks_helper.rb
module TicksHelper
end

app/views/makers/_form.html.erb
<div class="blue-background">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="xdp-logo-container">
				<div class="minibarra-logo">
					<p>
						<span>minibarra</span>
					</p>
				</div>
				<div class="xdp-logo">
					<p>
						<span>Experience</span><br>
						<span>Design</span><br>
						<span>Program</span>
					</p>
				</div>
			</div>
			
		</div>
	</div>
	<div class="container">
		<div class="col-md-6 col-md-offset-3 well signin">
		  <h4>Become a Maker</h4>

		  <%= simple_form_for @maker, validate: true do |f| %>

	  			<div class="first-name">
	          		<%= f.input :first_name, required: true, autofocus: true, label: false , :class => "input-lg", placeholder: "First name" %>
	        	</div>

		        <div class="last-name">
		         	<%= f.input :last_name, required: true, label: false, placeholder: "Last name (required)" %>
		        </div>

		        <%= f.input :email, required: true, label: false, placeholder: "Email (required)" %>

		    	<%= f.button :submit, "Get started", class: 'btn-primary btn-block btn-lg' %>
		  <% end %>
			
		  <%= flash_messages layout_flash: false %>

		</div>
			<div class="col-md-4 col-md-offset-4 well signin">
				<h4>What is this?</h4>
				<p>The Experience Design Program is how we choose what to work on next. </p>
				<hr>
				<h4>What are the benefits?</h4>
				<p>Members have a real impact on the direction of the product. As a bonus, all members get a 50% discount on Minibarra, provided you let Minibarra engineers visit you at work at least once a year.</p>
	</div>
	</div>

</div>	

app/views/makers/edit.html.erb
<% if user_signed_in? && current_user.admin == true %>
	<h1>Editing Maker</h1>

	<%= render 'form', maker: @maker %>

	<%= link_to 'Show', @maker %> |
	<%= link_to 'Back', makers_path %>
<% end %>

app/views/makers/index.html.erb
<% if user_signed_in? && current_user.admin == true %>
  <h1>Makers</h1>

  <table>
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @makers.each do |maker| %>
        <tr>
          <td><%= maker.first_name %></td>
          <td><%= maker.last_name %></td>
          <td><%= maker.email %></td>
          <td><%= link_to 'Show', maker %></td>
          <td><%= link_to 'Edit', edit_maker_path(maker) %></td>
          <td><%= link_to 'Destroy', maker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Maker', new_maker_path %>
<% end %>

app/views/makers/new.html.erb
<div class="maker-container">


	<%= render 'form', maker: @maker %>


</div>	

app/views/makers/show.html.erb
<% if user_signed_in? && current_user.admin == true %>
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>First name:</strong>
	  <%= @maker.first_name %>
	</p>

	<p>
	  <strong>Last name:</strong>
	  <%= @maker.last_name %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @maker.email %>
	</p>

	<%= link_to 'Edit', edit_maker_path(@maker) %> |
	<%= link_to 'Back', makers_path %>
<% end %>